services:

  postgres:
    image: postgres:15
    container_name: webhook_postgres
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_pass
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: